apiVersion: v1
kind: Service
metadata:
  name: nginxservice-4
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30091
  selector:
    app: nginx
    tier: display
